# The NumPy ndarray:

One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python. Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.


In [1]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 1.70711424, -0.00780693,  1.41368554],
       [ 1.78780451,  1.13125281, -0.00795743]])

Mathematical operations with data:

In [2]:
data * 10

array([[17.07114242, -0.07806926, 14.13685543],
       [17.87804513, 11.31252814, -0.0795743 ]])

In [3]:
data + data

array([[ 3.41422848, -0.01561385,  2.82737109],
       [ 3.57560903,  2.26250563, -0.01591486]])

An ndarray is a generic multidimensional container for homogeneous data; that is, all
of the elements must be the same type. Every array has a shape, a tuple indicating the
size of each dimension, and a dtype, an object describing the data type of the array:

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

## Creating ndarrays

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape
inferred from the data. We can confirm this by inspecting the ndim and shape
attributes:

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In addition to np.array, there are a number of other functions for creating new
arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a
given length or shape. empty creates an array without initializing its values to any particular value. 
To create a higher dimensional array with these methods, pass a tuple
for the shape:

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.empty((2, 3, 2))

array([[[1.03826195e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 1.33664410e+160]],

       [[5.00420339e-090, 3.27484594e+179],
        [6.54513258e-043, 1.59922997e+160],
        [3.99910963e+252, 4.04509213e-057]]])

__It’s not safe to assume that np.empty will return an array of all
zeros. In some cases, it may return uninitialized “garbage” values.__

arange is an array-valued version of the built-in Python range function:

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

You can explicitly convert or cast an array from one dtype to another using ndarray’s
astype method:

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [15]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

Floating-point numbers to integer dtype, the decimal part will be truncated:

In [16]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [17]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

If you have an array of strings representing numbers, you can use astype to convert
them to numeric form:

In [18]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

__Calling astype always creates a new array (a copy of the data), even
if the new dtype is the same as the old dtype.__

## Arithmetic with NumPy Arrays

Any arithmetic
operations between equal-size arrays applies the operation element-wise:


In [19]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [21]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propagate the scalar argument to each element in
the array:

In [22]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [23]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [24]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Comparisons between arrays of the same size yield boolean arrays:

In [25]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [26]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

One-dimensional arrays are simple; on
the surface they act similarly to Python lists:


In [27]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

If you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
propagated (or broadcasted henceforth) to the entire selection. An important first distinction from Python’s built-in lists is that array slices are views on the original array.
This means that the data is not copied, and any modifications to the view will be
reflected in the source array.

In [31]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Now, when I change values in arr_slice, the mutations are reflected in the original
array arr:

In [32]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

The “bare” slice [:] will assign to all values in an array:


In [33]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

__If you want a copy of a slice of an ndarray instead of a view, you
will need to explicitly copy the array—for example,
arr[5:8].copy().__

With higher dimensional arrays, you have many more options. In a two-dimensional
array, the elements at each index are no longer scalars but rather one-dimensional
arrays:

In [34]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

Individual elements can be accessed recursively. But that is a bit too much
work, so you can pass a comma-separated list of indices to select individual elements.
So these are equivalent:

In [35]:
arr2d[0][2]

3

In [36]:
arr2d[0, 2]

3

### Indexing with slices

In [37]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [38]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# select the first two rows of arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

You can pass multiple slices just like you can pass multiple indexes:

In [41]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

A colon by itself means to take the entire axis, so you can slice only higher dimensional axes by doing:

In [42]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

assigning to a slice expression assigns to the whole selection:

In [43]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [45]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [46]:
data

array([[ 0.3157424 ,  0.48432906,  1.58276321, -0.83536298],
       [ 0.59054629, -0.62682942,  0.05776601,  0.01598715],
       [-0.04461529,  0.36645246,  0.97852935, -0.11568767],
       [ 1.53157082,  0.11114096,  1.2506333 ,  0.25644025],
       [-0.81825988, -1.67306661, -0.48577036, -1.82430723],
       [-0.44330955, -1.01933055, -0.09803769, -0.98990702],
       [ 0.36562507, -1.2419268 ,  0.15738086, -0.62665508]])

In [47]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [48]:
data[names == 'Bob']

array([[ 0.3157424 ,  0.48432906,  1.58276321, -0.83536298],
       [ 1.53157082,  0.11114096,  1.2506333 ,  0.25644025]])

__The boolean array must be of the same length as the array axis it’s indexing.__

In [49]:
data[names == 'Bob', 2:]

array([[ 1.58276321, -0.83536298],
       [ 1.2506333 ,  0.25644025]])

In [50]:
data[names == 'Bob', 3]

array([-0.83536298,  0.25644025])

To select everything but 'Bob', you can either use != or negate the condition using ~:


In [51]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [52]:
data[~(names == 'Bob')]

array([[ 0.59054629, -0.62682942,  0.05776601,  0.01598715],
       [-0.04461529,  0.36645246,  0.97852935, -0.11568767],
       [-0.81825988, -1.67306661, -0.48577036, -1.82430723],
       [-0.44330955, -1.01933055, -0.09803769, -0.98990702],
       [ 0.36562507, -1.2419268 ,  0.15738086, -0.62665508]])

The ~ operator can be useful when you want to invert a general condition:

In [53]:
cond = names == 'Bob'
data[~cond]

array([[ 0.59054629, -0.62682942,  0.05776601,  0.01598715],
       [-0.04461529,  0.36645246,  0.97852935, -0.11568767],
       [-0.81825988, -1.67306661, -0.48577036, -1.82430723],
       [-0.44330955, -1.01933055, -0.09803769, -0.98990702],
       [ 0.36562507, -1.2419268 ,  0.15738086, -0.62665508]])

Selecting two of the three names to combine multiple boolean conditions, use
boolean arithmetic operators like & (and) and | (or):

In [54]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

_The Python keywords and and or do not work with boolean arrays.
Use __&__ (and) and __|__ (or) instead._

Selecting data from an array by boolean indexing always creates a copy of the data,
even if the returned array is unchanged.


Setting values with boolean arrays works in a common-sense way. To set all of the
negative values in data to 0 we need only do:

In [55]:
data[data < 0] = 0
data

array([[0.3157424 , 0.48432906, 1.58276321, 0.        ],
       [0.59054629, 0.        , 0.05776601, 0.01598715],
       [0.        , 0.36645246, 0.97852935, 0.        ],
       [1.53157082, 0.11114096, 1.2506333 , 0.25644025],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.36562507, 0.        , 0.15738086, 0.        ]])

Setting whole rows or columns using a one-dimensional boolean array is also easy:

In [56]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.59054629, 0.        , 0.05776601, 0.01598715],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.36562507, 0.        , 0.15738086, 0.        ]])

### Fancy Indexing


In [57]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select out a subset of the rows in a particular order, you can simply pass a list or
ndarray of integers specifying the desired order:

In [58]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Using negative indices selects rows from
the end:

In [59]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passing multiple index arrays does something slightly different; it selects a onedimensional array of elements corresponding to each tuple of indices:

In [75]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [61]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

## **Array Manipulation**

### **Shape**

In [83]:
#Flatten the array
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [84]:
#Reshape
arr.reshape(4, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

### <span style="color: var(--vscode-foreground);"><b>Concatenation</b></span>

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.concatenate((arr1, arr2)))  # Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]


### <span style="color: var(--vscode-foreground);"><b>Stacking Arrays</b></span>

In [91]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Vertical stacking
print(np.vstack((arr1, arr2)))  

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [92]:
# Horizontal stacking
print(np.hstack((arr1, arr2)))  

[[1 2 5 6]
 [3 4 7 8]]


### <span style="color: var(--vscode-foreground);"><b>Splitting Arrays</b></span>

In [89]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
print(np.array_split(arr, 3))

# 2D array split
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(np.hsplit(arr2, 3))   

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


### **Transposing Arrays and Swapping Axes**

Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. 
Arrays have the transpose method and also the
special T attribute:

In [62]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Computing the inner matrix product using np.dot:

In [64]:
arr = np.random.randn(6, 3)
arr

array([[ 0.89149983, -0.1730681 ,  0.69016842],
       [-1.33947885, -1.04573436, -1.11770286],
       [-0.86124593, -0.26178767, -0.6775262 ],
       [-0.62449125, -0.32288311, -0.57821005],
       [ 0.51104472,  0.45066708,  1.58840419],
       [ 0.19345132, -0.56883514,  1.59172422]])

In [65]:
np.dot(arr.T, arr)

array([[4.01929955, 1.79381924, 4.17669492],
       [1.79381924, 1.82297344, 1.22384921],
       [4.17669492, 1.22384921, 7.57557461]])

For higher dimensional arrays, transpose will accept a tuple of axis numbers to per‐
mute the axes (for extra mind bending):

In [66]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [67]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

_Here, the axes have been reordered with the second axis first, the first axis second,
and the last axis unchanged._

ndarray has the method
swapaxes, which takes a pair of axis numbers and switches the indicated axes to rearrange the data:


In [68]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [69]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## **Universal Functions**

In [71]:
# NumPy provides universal functions which operate element-wise on arrays.

arr = np.array([1, 2, 3, 4, 5])

print(np.sqrt(arr))  # Output: [1.         1.41421356 1.73205081 2.         2.23606798]
print(np.exp(arr))   # Output: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
print(np.sin(arr))   # Output: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


## **Aggregate Functions**

In [88]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sum(arr))          # Output: 21
print(np.mean(arr))         # Output: 3.5
print(np.min(arr))          # Output: 1
print(np.max(arr))          # Output: 6
print(np.std(arr))          # Output: 1.707825127659933
print(np.sum(arr, axis=0))  # Output: [5 7 9]
print(np.sum(arr, axis=1))  # Output: [ 6 15]

21
3.5
1
6
1.707825127659933
[5 7 9]
[ 6 15]


## **Linear Algebra**

In [93]:
from numpy.linalg import inv, det

# Matrix inversion
matrix = np.array([[1, 2], [3, 4]])
print(inv(matrix))

# Determinant
print(det(matrix)) 

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


## **Random**

In [96]:
# Generate random numbers
print(np.random.rand(3, 3))  # 3x3 matrix with random values between 0 and 1

[[0.3673713  0.83235371 0.35515607]
 [0.95219651 0.56363207 0.49368345]
 [0.24095285 0.99542876 0.30385172]]


In [97]:
# Random integers
print(np.random.randint(0, 10, (3, 3)))  # 3x3 matrix with random integers between 0 and 10

[[8 8 6]
 [7 3 3]
 [9 7 4]]


In [98]:
# Normal distribution
print(np.random.normal(0, 1, (3, 3)))  # 3x3 matrix with normally distributed values (mean=0, std=1)

[[-0.76308174  0.53944209  1.77192912]
 [-0.50041475 -0.63977491 -1.61595337]
 [ 1.10750481  1.04624606 -1.37154815]]


## **Files**

In [99]:
arr = np.array([1, 2, 3, 4, 5])

# Save to a file
np.save('my_array.npy', arr)

In [100]:
# Load from a file
loaded_arr = np.load('my_array.npy')
print(loaded_arr) 

[1 2 3 4 5]
